- DayTrade:
    call: http.post
    args:
        url: https://helloworld-s3yk5iivva-uc.a.run.app/dayend
        body:
            ticker1: GLD
            ticker2: IAU
            lot1: 1
            lot2: 5
            beta: 1
            res: 0
        auth:
            type: OIDC  